$file = 'E:\Android\SceneformEQR\Sceneform-EQR-main\Sceneform-EQR-main\Eq-Renderer\Android\eq-renderer\src\main\java\com\eqgis\eqr\layout\SceneLayout.java'
$lines = [System.IO.File]::ReadAllLines($file)
$output = New-Object System.Collections.Generic.List[string]

foreach ($line in $lines) {
    # Add MotionEvent import after Gravity
    if ($line -match 'import android\.view\.Gravity;') {
        $output.Add($line)
        $output.Add('import android.view.MotionEvent;')
        continue
    }
    
    # Add touch rotation fields after gestureDetector field
    if ($line -match 'private GestureDetector gestureDetector;') {
        $output.Add($line)
        $output.Add('')
        $output.Add('    // 触摸旋转相关')
        $output.Add('    private Node touchRotationTarget;')
        $output.Add('    private float lastTouchX = 0f;')
        $output.Add('    private float lastTouchY = 0f;')
        $output.Add('    private boolean isUserInteracting = false;')
        $output.Add('    private float currentRotationX = 0f;  // 绕X轴旋转角度（上下）')
        $output.Add('    private float currentRotationY = 0f;  // 绕Y轴旋转角度（左右）')
        $output.Add('    private float touchRotationSensitivity = 0.5f;  // 默认灵敏度')
        $output.Add('    private boolean touchRotationEnabled = false;')
        continue
    }
    
    # Add touch rotation methods before captureScreen javadoc
    if ($line -match '^\s+\*\s+截屏$') {
        # We're at the javadoc of captureScreen, insert methods before it
        # Remove the last added line (the "/**" line)
        $lastIdx = $output.Count - 1
        if ($lastIdx -ge 0 -and $output[$lastIdx] -match '/\*\*') {
            $output.RemoveAt($lastIdx)
        }
        
        $output.Add('    // ==================== 触摸旋转控制 ====================')
        $output.Add('')
        $output.Add('    /**')
        $output.Add('     * 启用触摸旋转控制')
        $output.Add('     * @param target 要旋转的目标节点')
        $output.Add('     * @param sensitivity 灵敏度（每像素旋转角度），建议0.3f-1.0f')
        $output.Add('     */')
        $output.Add('    public void enableTouchRotation(Node target, float sensitivity) {')
        $output.Add('        this.touchRotationTarget = target;')
        $output.Add('        this.touchRotationSensitivity = sensitivity;')
        $output.Add('        this.touchRotationEnabled = true;')
        $output.Add('        this.currentRotationX = 0f;')
        $output.Add('        this.currentRotationY = 0f;')
        $output.Add('    }')
        $output.Add('')
        $output.Add('    /**')
        $output.Add('     * 启用触摸旋转控制（默认灵敏度）')
        $output.Add('     * @param target 要旋转的目标节点')
        $output.Add('     */')
        $output.Add('    public void enableTouchRotation(Node target) {')
        $output.Add('        enableTouchRotation(target, 0.5f);')
        $output.Add('    }')
        $output.Add('')
        $output.Add('    /**')
        $output.Add('     * 禁用触摸旋转')
        $output.Add('     */')
        $output.Add('    public void disableTouchRotation() {')
        $output.Add('        this.touchRotationEnabled = false;')
        $output.Add('        this.touchRotationTarget = null;')
        $output.Add('    }')
        $output.Add('')
        $output.Add('    /**')
        $output.Add('     * 是否正在触摸交互中')
        $output.Add('     */')
        $output.Add('    public boolean isUserInteracting() {')
        $output.Add('        return isUserInteracting;')
        $output.Add('    }')
        $output.Add('')
        $output.Add('    /**')
        $output.Add('     * 应用当前旋转到目标节点')
        $output.Add('     */')
        $output.Add('    private void applyTouchRotation() {')
        $output.Add('        if (touchRotationTarget == null) return;')
        $output.Add('        // 组合旋转：先绕Y轴，再绕X轴')
        $output.Add('        Quaternion rotationY = new Quaternion(Vector3.up(), currentRotationY);')
        $output.Add('        Quaternion rotationX = new Quaternion(Vector3.right(), currentRotationX);')
        $output.Add('        touchRotationTarget.setLocalRotation(Quaternion.multiply(rotationY, rotationX));')
        $output.Add('    }')
        $output.Add('')
        $output.Add('    @Override')
        $output.Add('    public boolean onInterceptTouchEvent(MotionEvent ev) {')
        $output.Add('        if (touchRotationEnabled && touchRotationTarget != null) {')
        $output.Add('            if (ev.getAction() == MotionEvent.ACTION_DOWN) {')
        $output.Add('                lastTouchX = ev.getX();')
        $output.Add('                lastTouchY = ev.getY();')
        $output.Add('                isUserInteracting = true;')
        $output.Add('            }')
        $output.Add('        }')
        $output.Add('        return super.onInterceptTouchEvent(ev);')
        $output.Add('    }')
        $output.Add('')
        $output.Add('    @Override')
        $output.Add('    public boolean onTouchEvent(MotionEvent event) {')
        $output.Add('        if (touchRotationEnabled && touchRotationTarget != null) {')
        $output.Add('            switch (event.getAction()) {')
        $output.Add('                case MotionEvent.ACTION_DOWN:')
        $output.Add('                    lastTouchX = event.getX();')
        $output.Add('                    lastTouchY = event.getY();')
        $output.Add('                    isUserInteracting = true;')
        $output.Add('                    return true;')
        $output.Add('                case MotionEvent.ACTION_MOVE:')
        $output.Add('                    float deltaX = event.getX() - lastTouchX;')
        $output.Add('                    float deltaY = event.getY() - lastTouchY;')
        $output.Add('')
        $output.Add('                    // 水平拖动 -> 绕Y轴旋转')
        $output.Add('                    currentRotationY += deltaX * touchRotationSensitivity;')
        $output.Add('                    // 垂直拖动 -> 绕X轴旋转')
        $output.Add('                    currentRotationX -= deltaY * touchRotationSensitivity;')
        $output.Add('')
        $output.Add('                    // 限制X轴旋转角度，避免翻转过度')
        $output.Add('                    currentRotationX = Math.max(-90f, Math.min(90f, currentRotationX));')
        $output.Add('')
        $output.Add('                    // 应用旋转')
        $output.Add('                    applyTouchRotation();')
        $output.Add('')
        $output.Add('                    lastTouchX = event.getX();')
        $output.Add('                    lastTouchY = event.getY();')
        $output.Add('                    return true;')
        $output.Add('                case MotionEvent.ACTION_UP:')
        $output.Add('                case MotionEvent.ACTION_CANCEL:')
        $output.Add('                    isUserInteracting = false;')
        $output.Add('                    return true;')
        $output.Add('            }')
        $output.Add('        }')
        $output.Add('        return super.onTouchEvent(event);')
        $output.Add('    }')
        $output.Add('')
        $output.Add('    /**')
        $output.Add($line)
        continue
    }
    
    $output.Add($line)
}

[System.IO.File]::WriteAllLines($file, $output.ToArray())
Write-Host "SceneLayout.java modified successfully. Total lines: $($output.Count)"
